#!/bin/bash

# accepts arg for minute period, calls the tweet script
# runs at interval as defined within the config file

# sets the path to the csv file in which wifi down data
# is stored
wifiCSV="/usr/local/projects/wifi_connectivity_bot/Record_Keeping/up_down_wifi.csv"


interval="$1"
earliestDate="$(date "+%Y-%m-%d %H:%M:%S" -d "-$interval days")"
# assumed one down time due to the fact the script was called.
counter=0

cat $wifiCSV | sed '1,2d' | ( while read -r line
do
   lineStatus=$(echo $line | awk -F "," '{print $1}')
   lineSec=$(echo $line | awk -F "," '{print $2}')
   lineMin=$(echo $line | awk -F "," '{print $3}')
   lineHour=$(echo $line | awk -F "," '{print $4}') 
   lineDay=$(echo $line | awk -F "," '{print $5}')
   lineMonth=$(echo $line | awk -F "," '{print $6}')
   lineYear=$(echo $line | awk -F "," '{print $7}')
   
   # has 0 for seconds to prevent from issues with time comparisons
   lineDate=$(date -d "$lineYear-$lineMonth-$lineDay $lineHour:$lineMin:0" +'%Y-%m-%d %H:%M:%S')
   earlDateSec=$(date -d "$earliestDate" +%s)
   lineDateSec=$(date -d "$lineDate" +%s)
   
  
   if [ "$lineStatus"=="OFFLINE" ] && [ "$earlDateSec" -lt "$lineDateSec"  ]
   then
      counter=$(($counter + 1))
   fi
done

echo -n "$counter" )
