#!/bin/bash
# config path set to config/ dir because the script is called from main dir
config="config/config_file.txt"

if [ "$1" == 1 ]
then
   echo -n $(grep "Wifi Interface:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 2 ]
then
   echo -n $(grep "Wifi Network Name:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 3 ]
then
   echo -n $(grep "Ethernet Interface:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 4 ]
then
   echo -n $(grep "Twitter Destination:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 5 ]
then
   echo -n $(grep "Consumer Key:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 6 ]
then
   echo -n $(grep "Consumer Secret:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 7 ]
then
   echo -n $(grep "Access Token Key:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 8 ]
then
   echo -n $(grep "Access Token Secret:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 9 ]
then
   echo -n $(grep "Tweet Interval:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 10 ]
then
   echo -n $(grep "Target Threshold:" $config | awk -F ":" '{print $2}')
elif [ "$1" == 11 ]
then
   echo -n $(grep "Wrapup Frequency:" $config | awk -F ":" '{print $2}')
fi
