#!/bin/bash
csvFile="/usr/local/projects/wifi_connectivity_bot/record-keeping/up_down_eth.csv"
result="$(cat $csvFile | sed 1,2d | tail -1 | awk -F ',' '{print $1}')"
if [ "$result" != "ONLINE" ] && [ "$result" != "OFFLINE" ] 
then
   echo -n "1"
elif [ "$1" == "0" ]
then
   if [ "$result" == "OFFLINE" ]
   then
      echo -n "1"
   else
      echo -n "0"
   fi
else
   if [ "$result" == "ONLINE" ]
   then
      echo -n "1"
   else
      echo -n "0"
   fi
fi
