#!/bin/bash
# arg 1 = connected boolean, arg2 =ethernet boolean
if [ "$2"=="0" ]
then
   csvFile="/usr/local/projects/wifi_connectivity_bot/record-keeping/up_down_eth.csv"
else
   csvFile="/usr/local/projects/wifi_connectivity_bot/record-keeping/up_down_wifi.csv"
fi

result="$(cat $csvFile | tail -n +3 | tail -1 | awk -F ',' '{print $1}')"
if [ "$result" != "ONLINE" ] && [ "$result" != "OFFLINE" ] 
then
   echo -n "1"
elif [ "$1" == "0" ]
then
   if [ "$result" == "OFFLINE" ]
   then
      echo -n "1"
   else
      echo -n "0"
   fi
else
   if [ "$result" == "ONLINE" ]
   then
      echo -n "1"
   else
      echo -n "0"
   fi
fi
