#!/bin/bash

# accepts arg for minute period, calls the tweet script
# runs at interval as defined within the config file

# sets the path to the csv file in which wifi down data
# is stored
wifiCSV="record-keeping/up_down_wifi.csv"

interval="$1"
earliestDate="$(date "+%m-%d-%Y %H:%M:%S" -d "-$interval days")"

echo "$earliestDate"

counter=0

cat $wifiCSV | sed '2d' | while read -r line
do
   lineStatus=$(echo $line | awk -F "," '{print $1}')
   lineSec=$(echo $line | awk -F "," '{print $2}')
   lineMin=$(echo $line | awk -F "," '{print $3}')
   lineHour=$(echo $line | awk -F "," '{print $4}') 
   lineDay=$(echo $line | awk -F "," '{print $5}')
   lineMonth=$(echo $line | awk -F "," '{print $6}')
   lineYear=$(echo $line | awk -F "," '{print $7}')
   
   lineDate=$(date -d "$lineYear-$lineMonth-$lineDay $lineHour:$lineMin:$lineSec")

   if [ "$lineStatus"=="OFFLINE" ] && [ "$earliestDate" -lt "$lineDate"  ]
   then
      counter=$(($counter + 1))
   fi
done

echo -n "$counter"
