#!/bin/bash

# path setting
recordPath="/usr/local/projects/wifi_connectivity_bot/record-keeping/"
ethCSV=$recordPath"up_down_eth.csv"
wifiCSV=$recordPath"up_down_wifi.csv"
logFile=$recordPath"log_file.txt"
temp=$recordPath"temp.txt"

# Description: used for clearing logs 
# Args: $1 = input file, $2 = num lines at top
function clear_log()
{
   cat $1 | head -$2 > $temp
   mv $temp $1
}

clear_log $ethCSV 2
clear_log $wifiCSV 2
clear_log $logFile 1
